### ISSUE TITLE
Clean install dnscrypt-proxy.toml error

### ISSUE THREAD

**Issue by nosize** [thuantran/dnscrypt-asuswrt-installer#151]
When you install dnscrypt cleanly, an error occurs in dnscrypt-proxy.toml and it becomes dnscrypt-proxy.toml.err

https://dropmefiles.com/UiZce

**Comment by Zastoff** [comment]
Was issues with arm binaries in version 2.0.40
It was later on fixed, And now version 2.0.42 is out

**Comment by nosize** [comment]
Thanks, really the problem was in version 2.0.40
