### ISSUE TITLE
How to enable DoH ?

### ISSUE THREAD

**Issue by HysanDev** [thuantran/dnscrypt-asuswrt-installer#152]
I visited Cloudflare website (https://www.cloudflare.com/ssl/encrypted-sni/)
and said it is using 1.1.1.1 (well in fact 1.1.1.2 for security), but not over a secure dns query.
Just wondering how can we enable DNS over HTTPS?

**Comment by jumpsmm7** [comment]
Are you using a built in dnssec validator? If so then cloudflare test will always fail because it breaks their test and says you are not using https. The only way to truly tell if you are not using https is to observe your ports coming in and going out at both 443 and port 53.

**Comment by jumpsmm7** [comment]
Or turn off dnssec validation and try redoing the test you will see it says you are using Doh.
