### ISSUE TITLE
Server criteria ignored?

### ISSUE THREAD

**Issue by b9AcE** [thuantran/dnscrypt-asuswrt-installer#194]
While running the installer's configuration, I answered the following prompts accordingly:

Do you want to use DNS server over IPv6 (yes only if your connection has IPv6)? [y/n]: n
Choose how your DNS servers are selected: 1) Automatically
Use only servers that support the DNSCrypt protocol [y/n]: n
Use only servers that support the DNS-over-HTTPS protocol [y/n]: y
Use only servers that support DNSSEC [y/n]: y
Use only servers that do not log user's queries [y/n]: y
Use only servers that do not filter result [y/n]: y
Do you want to choose which servers to disable (this can be a long process)? [y/n]: y

Result: 175 servers listed, including IPv6, including filtering (against ads/malware/etc) enabled, including without DNSSEC, including DNSCrypt servers (not providing DoH).

I would have expected the list to ONLY include those that fulfill the criteria of being known to not filter anything at all, not log anything, provide DoH service with DNSSEC capability and to exclude all IPv6-servers.
I would also expect those answers to result in exclusion from the list those whose service is unknown, e.g. if they do not explicitly declare to not filter anything.
Deselecting DNSCrypt in the criteria above was done as a test for this GitHub issue, as I actually DO want those too, but whether I chose "yes" or "no" to that question, they always show up in the list.

This is on an RT-AC86U running Asuswrt-Merlin version 384.19 and "dnscrypt installer" version 2.1.7 (but also the previous version) as installed by amtm version 3.1.8.

**Comment by Zastoff** [comment]
The logic in the public-resolvers.md is not the best and is hard to filter perfectly.

"Do you want to use DNS server over IPv6 (yes only if your connection has IPv6)? [y/n]: n"
The list may display some IPv6 servers but the proxy will **not use** it even if manually chosen.

**Comment by jumpsmm7** [comment]
Okay this is an Issue you must open up with dnscrypt-proxy 2 itself. The installer list the criteria the user specifies within the .TOML file. Dnscrypt-Proxy 2 itself is responsible for honoring it. IF dnscrypt-proxy 2 is not honoring it an issue such as this should be open with Dnscrypt-Proxy 2 page. Their page is found here. I hope this helps.
https://github.com/DNSCrypt/dnscrypt-proxy
