### ISSUE TITLE
How to know if your router supports HW RNG

### ISSUE THREAD

**Issue by gbaoye** [thuantran/dnscrypt-asuswrt-installer#195]
In other words, all ASUS routers support

**Comment by Zastoff** [comment]
[https://onerng.info/](url) with something like that i guess HW RNG can be used, Do not think any Asus router has one built in.
I use the installers HAVEGED RNG

**Comment by jumpsmm7** [comment]
Let it be noted this script only supports  asus routers flashed with A current Rmerlin Asuswrt firmware because it relies on custom scripts.
