### ISSUE TITLE
Support for RT-AC86U

### ISSUE THREAD

**Issue by Tom-Jojo** [thuantran/dnscrypt-asuswrt-installer#2]
Hi,

Will the RT-AC86U be supported?

/Tom

**Comment by thuantran** [comment]
I will, I'm checking if dnscrypt-proxy v2 is good and will update the script for this as well.

**Comment by thuantran** [comment]
Hi there,

I need your help running this command "uname -m" on ssh shell and send me the result.

Best regards,
Thuan

**Comment by Tom-Jojo** [comment]
Hi Sir,

It returns: aarch64

Brgds
Tom

**Comment by thuantran** [comment]
Please follow this link to try the new BETA to see if it works on your platform.
https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/page-19#post-375531

**Comment by Tom-Jojo** [comment]
Hi,
It seems it cannot reach the ntp server when enabled. I get the following in the log over and over:
Feb 14 01:03:30 ntp: start NTP update

I have google 8.8.4.4 and 8.8.8.8 blocked, but cisco was selected as DNS server from the list.

**Comment by thuantran** [comment]
I use Google DNS as bootstrap for some resolving that needs to be done to init dnscrypt-proxy and firmware services (like ntp). If you block that, then of course you will have problem.

**Comment by Tom-Jojo** [comment]
Ahh ok, I need to block those at router level to use region unlock in Netflix and Hulu etc.

**Comment by thuantran** [comment]
Hum, I see your use case. I will make that configurable in a new version then.

**Comment by thuantran** [comment]
I have updated the code to allow you to set a different DNS to init. Please try to run the beta installer again.
