### ISSUE TITLE
Getting Bad Address on Downloading

### ISSUE THREAD

**Issue by KCAS** [thuantran/dnscrypt-asuswrt-installer#27]
Info:  Downloading dnscrypt-proxy-linux_mipsle-2.0.3.tar.gz
installer: line 809: echo: Bad address
 Info:  Downloading public-resolvers.md
installer: line 809: echo: Bad address

doing fresh install.

on google dns 8.8.8.8/8.8.4.4 tried also on isp dns
rt-n66u
john's fork of merlin firmware
374.43_30E3j9527

**Comment by thuantran** [comment]
Check this issue https://github.com/thuantran/dnscrypt-asuswrt-installer/issues/26 , in short dnscrypt-proxy installer  for version 2 does not work on MIPS router.
