### ISSUE TITLE
RT-AC86U: Binaries nonroot and haveged not working

### ISSUE THREAD

**Issue by Caribpa** [thuantran/dnscrypt-asuswrt-installer#29]
Hi,
After installing dnscrypt on my RT-AC86U using your script I found myself in the [same position](https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/page-38#post-384538) as the SNBForum user Andy1932.

After doing some tests I found out that both the **nonroot** and **haveged** binaries don't work. When executing them individually the shell returns:
```sh
admin@RT-AC86U-6208:/jffs/dnscrypt# /jffs/dnscrypt/nonroot
-sh: /jffs/dnscrypt/nonroot: not found
admin@RT-AC86U-6208:/jffs/dnscrypt# /jffs/dnscrypt/haveged
-sh: /jffs/dnscrypt/haveged: not found
```
Which means that the start of dnscrypt, _line 35_ of the file **manager**, will always fail:
```sh
admin@RT-AC86U-6208:/jffs/dnscrypt# /jffs/dnscrypt/nonroot nobody /jffs/dnscrypt/dnscrypt-proxy -syslog -config /jffs/dnscrypt/dnscrypt-proxy.toml
-sh: /jffs/dnscrypt/nonroot: not found
```
And the same applies for the _line 101_ when executing haveged.

Note that the binaries are in the folder:
```sh
admin@RT-AC86U-6208:/jffs/dnscrypt# ls -l /jffs/dnscrypt
-rw-r--r--    1 admin    root           818 Feb 27 08:54 LICENSE
-rwxr-xr-x    1 admin    root       6547488 Feb 27 09:01 dnscrypt-proxy
-rw-r--r--    1 admin    root         10524 Mar  2 13:45 dnscrypt-proxy.toml
-rw-r--r--    1 admin    root           782 Feb 27 08:54 example-blacklist.txt
-rw-r--r--    1 admin    root           731 Feb 27 08:54 example-cloaking-rules.txt
-rw-r--r--    1 admin    root         10354 Feb 27 08:54 example-dnscrypt-proxy.toml
-rw-r--r--    1 admin    root           496 Feb 27 08:54 example-forwarding-rules.txt
-rwxr-xr-x    1 admin    root        109272 Mar  2 13:27 haveged
-rw-r--r--    1 admin    root          3453 Jan 24 06:55 localtime
-rwxr-xr-x    1 admin    root          3085 Mar  2 14:39 manager
-rwxr-xr-x    1 admin    root          3568 Mar  2 13:25 nonroot
-rw-r--r--    1 nobody   nobody       18658 Mar  2 13:25 public-resolvers.md
-rw-r--r--    1 nobody   nobody         307 Mar  2 13:25 public-resolvers.md.minisig
```

Temporary I've changed the manager's script so dnscrypt is executed but with admin privileges, making everything work as supposed but I'd like to run it with non root privileges.

Thank you very much.

**Comment by thuantran** [comment]
Thanks for the debugging.

I need to procure a 86U to try to fix this, so this issue will have to wait unfortunately.

**Comment by thuantran** [comment]
Still couldn't get my hands on a 86U, but I compiled for armv8 blind.

Please try the binaries available here https://github.com/thuantran/dnscrypt-asuswrt-installer/tree/dev/armv8 and tell me how it goes.
Remember to chmod 755 the files you replaced.

**Comment by Caribpa** [comment]
Perfect, this solves the issue.

Here it can be seen that haveged is working and dnscrypt is running as nobody:
```sh
admin@RT-AC86U-6208:/tmp/home/root# ps w | grep dnscrypt
  709 admin     7532 S    /jffs/dnscrypt/haveged -w1024 -v1
  712 admin     3120 S    {manager} /bin/sh /jffs/dnscrypt/manager monitor-start
 1135 nobody    9732 S    /jffs/dnscrypt/dnscrypt-proxy -syslog -config /jffs/dnscrypt/dnscrypt-proxy.toml
```
I've tried to execute the other binaries and everything works, no more `not found` error.

Nice work, thank you very much :)

**Comment by thuantran** [comment]
Thanks for confirmation. I have updated the mainline code so the installation should work again.
