### ISSUE TITLE
$URL_ARCH is undefined

### ISSUE THREAD

**Issue by BryceReedman** [thuantran/dnscrypt-asuswrt-installer#342]
There are references to the URL_ARCH variable in the installer script however it is not defined.

I cannot install HAVAGE through the script as it fails to download.

Running a RT-AX58U latest asuswrt-merlin firmware.

**Comment by jumpsmm7** [comment]
> 

You don't need to install haveged, it is installed by default on every asuswrt-merlin router since 2 or 3 firmware releases ago.
And what version of Rmerlin firmware are you using?

**Comment by jumpsmm7** [comment]
fixed with this commit https://github.com/thuantran/dnscrypt-asuswrt-installer/pull/344
