### ISSUE TITLE
Error:  Unable to detect the Internet!

### ISSUE THREAD

**Issue by josh-aliencode** [thuantran/dnscrypt-asuswrt-installer#398]
When I try to install the script through **amtm** on the latest version of **merlin** on hardware **gt-ax6000**
I hit 1 to install
=>  Do you want to install dnscrypt-proxy to /jffs? [y/n]: **y**

 *** Error:  Unable to detect the Internet!
 Info:  Operation aborted. You can quit or continue
=====================================================

Any ideas?

**Comment by jumpsmm7** [comment]
@josh-aliencode
What value to you get in the SSH terminal, when you try to run?
`curl -sL "https://api.github.com/repos/jedisct1/dnscrypt-proxy/releases/latest" | grep "tag_name" | head -1 | cut -d \" -f 4`

**Comment by josh-aliencode** [comment]
I tried the command, nothing came up.. so I tried refining the command a bit..
curl -sL "https://api.github.com/repos/jedisct1/dnscrypt-proxy/releases/latest"
{"message":"API rate limit exceeded for 68.149.244.219. (But here's the good new                                                                                                    s: Authenticated requests get a higher rate limit. Check out the documentation f                                                                                                    or more details.)","documentation_url":"https://docs.github.com/rest/overview/re                                                                                                    sources-in-the-rest-api#rate-limiting"}

So I guess this explains everything. I guess I'm hammering Github. I'll have to try again later after limiting some of those requests.

**Comment by jumpsmm7** [comment]
@josh-aliencode 
At least you have some idea of the issue. Your ratelimit could potentially hinder you from properly downloading the dnscrypt-binaries as well since they are hosted on the github release section.

**Comment by josh-aliencode** [comment]
I don't suppose the script has a variable I can store my github token in?

**Comment by josh-aliencode** [comment]
I really appreciate your help! :-)
I've completely blocked github.com on my network.. i'll let that sit for a bit.. enable it again. And run thr script right aeay. Lol

**Comment by jumpsmm7** [comment]
@josh-aliencode 
I will leave this open pending your successful feed back.

**Comment by josh-aliencode** [comment]
Confirmed, The script installed properly.. :-)
Thanks again!
