### ISSUE TITLE
DNS leaks

### ISSUE THREAD

**Issue by D34DC3N73R** [thuantran/dnscrypt-asuswrt-installer#4]
I'm seeing my ISP (TWC) DNS servers along with the chosen DNScrypt server at https://www.dnsleaktest.com after reboots and a reinstall on an RT-AC88u. Can anyone else confirm?

**Comment by D34DC3N73R** [comment]
Found the issue to be the Merlin 382.1_2 release. Reverted back to 380.69 and DNScrypt functions as intended.

**Comment by thuantran** [comment]
Hi there,

I  have been busy with stuffs thus the silence. I'm in the process of rewriting this installer script for dnscrypt-proxy v2, this issue will be considered although low priority as the >= 382 branch for my AC56U is kinda suck from the things I have read on merlin forum.

BR,
thuan

**Comment by thuantran** [comment]
Likely same issue https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/page-30#post-378807

**Comment by thuantran** [comment]
The issued in  linked from tthe forum is fixed in the latest beta at https://www.snbforums.com/threads/release-dnscrypt-installer-for-asuswrt.36071/page-19#post-375531 . Hopefully the same issue reported here, otherwise I will reopen it.
