### ISSUE TITLE
dnscrypt does not start on RT-AX58U + can't be uninstalled

### ISSUE THREAD

**Issue by Helios12345** [thuantran/dnscrypt-asuswrt-installer#428]
Hi,

i installed dnscrypt on my RT-AX58U, but it does not start up and i can't uninstall it.
Since that my guest wifi's with VPN (YazFi) are not working anymore :-/
Can you help me how to uninstall it manually?

Thanks!

Merlin 388.2_2
dnscrypt 2.4.8

**Comment by Helios12345** [comment]
[dnscrypt_log.txt](https://github.com/thuantran/dnscrypt-asuswrt-installer/files/12174253/dnscrypt_log.txt)

**Comment by jumpsmm7** [comment]
> [dnscrypt_log.txt](https://github.com/thuantran/dnscrypt-asuswrt-installer/files/12174253/dnscrypt_log.txt)

Please try 
![68747470733a2f2f692e6962622e636f2f66743647566d632f696d6167652e706e67](https://github.com/thuantran/dnscrypt-asuswrt-installer/assets/49514613/e273fdca-02cf-4f30-8c8e-d2fea70529b8)
Option 8 of the installer.
