### ISSUE TITLE
Cloudflare 1.1.1.1 DNS over TLS 

### ISSUE THREAD

**Issue by conblem** [thuantran/dnscrypt-asuswrt-installer#54]
Hi

I just installed your script on my RT-3200 and everything installed without errors.
My Problem now is i can't get DNS over TLS to work when using 1.1.1.1 as a DNS server,
the communication is over port 53.
[Cloudflare DNS over TLS](https://developers.cloudflare.com/1.1.1.1/dns-over-tls/)

Nevertheless, awesome script and very easy to install!

```
dig google.com

; <<>> DiG 9.9.7-P3 <<>> google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 22250
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		216	IN	A	172.217.22.46

;; Query time: 4 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Sun Jun 24 20:09:39 CEST 2018
;; MSG SIZE  rcvd: 55
```

**Comment by thuantran** [comment]
dnscrypt-proxy does not support DNS over TLS only DNS over HTTP/2 and that works by default with my script. Also as the router still run dnsmasq caching after dnscrypt-proxy the request is still on 53.
