### ISSUE TITLE
Editing dnsmasq.conf.add instead of dnsmasq.conf in manager?

### ISSUE THREAD

**Issue by zmz125000** [thuantran/dnscrypt-asuswrt-installer#65]
(I thank) It would be better to edit dnsmasq.conf.add and dnsmasq.postconf instead of editing dnsmasq.conf directly in "/jffs/dnscrypt/manager". Thanks.

https://github.com/RMerl/asuswrt-merlin/wiki/Custom-config-files

**Comment by thuantran** [comment]
Well that manager script is called from dnsmasq.conf.postconf . I believe it is what you asked for already, doesn't it?
