### ISSUE TITLE
Update to Dnscrypt-proxy 2.0.20

### ISSUE THREAD

**Issue by vic958420** [thuantran/dnscrypt-asuswrt-installer#68]
Just released: https://github.com/jedisct1/dnscrypt-proxy/releases/tag/2.0.20

**Comment by crkinard** [comment]
And there seems to be an issue with 2.0.20

Throws the error:
`Mar 15 23:38:14 admin: Warning: dnscrypt-proxy is not responding`

Then restarts. Repeats forever.
