### ISSUE TITLE
Updated to 2.0.36 version Working to include Anonymized DNS support through menu option.

### ISSUE THREAD

**Issue by delusion2019** [thuantran/dnscrypt-asuswrt-installer#73]
It would be great to have the installer and the menu have a new option to choose between Anonymized DNS servers 

https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.0.29-beta.2

**Comment by jumpsmm7** [comment]
Version has been updated. do you have any suggestions for adding menu options for Anonymized dns support? I have been working to add it in.

**Comment by jumpsmm7** [comment]
Added Menu support for server_name"*" as an Option

**Comment by jumpsmm7** [comment]
Finished adding a menu for Relays per server.
